apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: production
data:
  index.html: |
    <html>
      <body style="font-family: Arial;">
        <h1>ROLLING UPDATE SUCCESS ðŸš€</h1>
        <p>ConfigMap updated live</p>
        <p>No image rebuild</p>
        <p>No service downtime</p>
      </body>
    </html>
