replicasCount: 3

image:
  repository: ghcr.io/adiforstudy/webapp
  tag: "788b9d302f1ac4fb686f922e32dcae4287a26ab2"
  pullPolicy: Always

config:
  enabled: true
  indexHtml: |
    <h1>PRODUCTION ENVIRONMENT</h1>

ingress:
  enabled: true
  host: webapp-prod.local

resources:
  requests: 
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
