replicaCount: 3

image:
  repository: ghcr.io/adiforstudy/webapp
  tag: latest

service:
  type: ClusterIP
  port: 80

config:
  enabled: true
  indexHtml: |
    <html>
      <body>
        <h1>GitOps Works ðŸš€</h1>
      </body>
    </html>

ingress:
  enabled: false

httpRoute:
  enabled: false

autoscaling:
  enabled: false
