replicasCount: 3

config:
  enabled: true
  indexHtml: |
    <h1>PRODUCTION ENVIRONMENT</h1>

ingress:
  enabled: true

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
